### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by satyamsah** [habib-rangoonwala/golang#1]
Hi Habib,

Sorry for spamming you. I am a university grad student and I am in novice phase of learning golang. I am trying to implement concurrent word count from different files. As it is already implemented by you, could you please help me to walk me through your code as you used a good amount of goroutines and channels which was convoluted for beginner like me.

**Comment by habib-rangoonwala** [comment]
Thanks for contacting me, I have very little information as to what you know and what you do not so it is really tough for me to write it here, in any case, i have referred to these links when i was learning about channels and parallel processing: hope it helps:

https://gobyexample.com/channels
https://tour.golang.org/concurrency/2
https://tour.golang.org/concurrency/3
https://tour.golang.org/concurrency/4
...
https://tour.golang.org/concurrency/11

https://golangbot.com/channels/

thanks and regards
-Habib
